# Generated by Django 2.1.3 on 2018-11-16 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('removal_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_price', models.IntegerField(blank=True, null=True)),
                ('receiving_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
