# Generated by Django 2.1.3 on 2018-11-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='name',
            field=models.CharField(default='banner', max_length=120),
        ),
        migrations.AddField(
            model_name='banner',
            name='no_of_installments',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installmentnumber', to='banner.installment'),
        ),
    ]
