# Generated by Django 2.1.3 on 2018-11-16 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banner', '0002_auto_20181116_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='no_of_installments',
        ),
        migrations.AddField(
            model_name='banner',
            name='number_of_installments',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='installment',
            name='banner_linked_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='installmentnumber', to='banner.banner'),
        ),
    ]
